version: '3.7'

services: 
    postgres:
        image: postgres:9.6
        container_name: postgreSQL
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: passwd
            POSTGRES_DB: airflow
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    init:
        image: apache/airflow:1.10.10
        container_name: airflow_initializer
        env_file: 
            - ./common.env
        depends_on: 
            - postgres
        command: initdb
