version: '3.7'

services: 
    postgres:
        image: postgres:9.6
        container_name: postgreSQL
        env_file: 
            - ./postgres.env
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    init:
        image: apache/airflow:1.10.10
        container_name: airflow_initializer
        env_file: 
            - ./airflow_common.env
        depends_on: 
            - postgres
        command: initdb
