version: '3.7'

services: 
    postgres:
        image: postgres:9.6
        container_name: postgreSQL
        env_file: 
            - ./postgres.env
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    redis:
        image: redis:5.0.9
        container_name: redis
        ports: 
            - "6379:6379"
        

    webserver:
        image: apache/airflow:1.10.10
        container_name: airflow_webserver
        env_file: 
            - ./airflow_common.env
        depends_on: 
            - postgres
        command: webserver
        ports: 
            - 8080:8080
        volumes: 
            - ./dags:/opt/airflow/dags
            - ./credentials.json:/app/credentials.json

    scheduler:
        image: apache/airflow:1.10.10
        container_name: airflow_scheduler
        env_file: 
            - ./airflow_common.env
        depends_on: 
            - postgres
        command: scheduler
        volumes: 
            - ./dags:/opt/airflow/dags
            - ./credentials.json:/app/credentials.json
    
    worker:
        image: apache/airflow:1.10.10
        container_name: airflow_worker
        env_file:
            - ./airflow_common.env
        command: worker -q ML
        volumes:
            - ./dags_worker:/opt/airflow/dags
            - ./credentials.json:/app/credentials.json

